import secrets
import string


CASE_ID_ALPHABET = string.ascii_uppercase + string.digits
CASE_ID_LENGTH = 16


def generate_case_id() -> str:
    """Return a non-sequential case ID generated by the OS CSPRNG."""
    return "".join(
        secrets.choice(CASE_ID_ALPHABET)
        for _ in range(CASE_ID_LENGTH)
    )
