-- Core PostgreSQL schema for the database-provisioning task.

CREATE TABLE IF NOT EXISTS auditors (
    auditor_id VARCHAR(50) PRIMARY KEY,
    login_hash TEXT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'auditor',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_auditors_role
        CHECK (role IN ('auditor', 'manager'))
);

CREATE TABLE IF NOT EXISTS cases (
    case_id VARCHAR(20) PRIMARY KEY,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    assigned_auditor_id VARCHAR(50)
        REFERENCES auditors(auditor_id) ON DELETE SET NULL,

    -- Storage reference only. Upload/storage behavior is implemented later.
    video_storage_path TEXT,

    -- Nullable placeholders for later AI-pipeline output.
    watson_severity_score INTEGER,
    effective_severity_score INTEGER,
    severity_tier VARCHAR(2),
    narrative_summary TEXT,
    incident_timeline JSONB,
    video_duration_seconds DOUBLE PRECISION,
    analysis_output_path TEXT,
    ai_failure VARCHAR(30),

    -- Nullable fields for the later review and final-outcome workflow.
    auditor_severity_score INTEGER,
    auditor_comment TEXT,
    final_outcome VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,

    CONSTRAINT ck_cases_status CHECK (
        status IN (
            'SUBMITTED',
            'AI_PROCESSING',
            'READY_FOR_REVIEW',
            'AUDITOR_REVIEW',
            'COMPLETE'
        )
    ),
    CONSTRAINT ck_cases_watson_severity_score CHECK (
        watson_severity_score IS NULL
        OR watson_severity_score BETWEEN 0 AND 100
    ),
    CONSTRAINT ck_cases_effective_severity_score CHECK (
        effective_severity_score IS NULL
        OR effective_severity_score BETWEEN 0 AND 100
    ),
    CONSTRAINT ck_cases_auditor_severity_score CHECK (
        auditor_severity_score IS NULL
        OR auditor_severity_score BETWEEN 0 AND 100
    ),
    CONSTRAINT ck_cases_severity_tier CHECK (
        severity_tier IS NULL
        OR severity_tier IN ('S1', 'S2', 'S3', 'S4')
    ),
    CONSTRAINT ck_cases_final_outcome CHECK (
        final_outcome IS NULL
        OR final_outcome IN (
            'NO_VIOLATION_FOUND',
            'POLICY_VIOLATION_FOUND'
        )
    ),
    CONSTRAINT ck_cases_ai_failure CHECK (
        ai_failure IS NULL
        OR ai_failure IN ('vision', 'speech_to_text')
    )
);

-- Keep existing databases compatible when this schema is explicitly reapplied.
ALTER TABLE cases ADD COLUMN IF NOT EXISTS video_duration_seconds DOUBLE PRECISION;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS analysis_output_path TEXT;
ALTER TABLE cases ADD COLUMN IF NOT EXISTS ai_failure VARCHAR(30);
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_cases_ai_failure'
    ) THEN
        ALTER TABLE cases ADD CONSTRAINT ck_cases_ai_failure
            CHECK (ai_failure IS NULL OR ai_failure IN ('vision', 'speech_to_text'));
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id VARCHAR(20) NOT NULL
        REFERENCES cases(case_id) ON DELETE RESTRICT,
    actor VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    before_value JSONB,
    after_value JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cases_assigned_auditor_id
    ON cases(assigned_auditor_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_case_id
    ON audit_logs(case_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
    ON audit_logs(created_at);
